# Generated by Django 3.1 on 2020-10-25 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'event_participants',
            },
        ),
        migrations.RemoveField(
            model_name='gameevents',
            name='medal',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sex',
            field=models.CharField(max_length=1),
        ),
        migrations.DeleteModel(
            name='Sex',
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.athlete'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='game_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gameevents'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='medal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.medal'),
        ),
    ]
