# Generated by Django 3.1 on 2020-10-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201024_2254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AthleteGame',
        ),
    ]
