# Generated by Django 3.1 on 2020-10-25 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_athletegame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
    ]
