# Generated by Django 3.1 on 2020-10-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201025_2210'),
        ('core', '0004_remove_city_country'),
    ]

    operations = [
    ]
